version: '2'
services:
  db:
    image: postgres
  web:
    build: . 
    command: gunicorn -w 4 --bind 0.0.0.0:8000 farma.wsgi:application
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - rabbit
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    volumes_from:
      - web
    links:
      - web:web

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

