version: '2'
services:
  db:
    image: postgres
  web:
    build: . 
    command: gunicorn -w 4 --bind 0.0.0.0:8000 farma.wsgi:application
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    volumes_from:
      - web
    links:
      - web:web
