version: '2'
services:
  db:
    image: postgres    
  web:
    build: ./web 
    command: ./web/run_web.sh
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - rabbit
    environment:
      - NOMBRE_DB=postgres
      - USUARIO_DB=postgres
      - HOST_DB=db
      - PORT_DB=5432
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    volumes_from:
      - web
    depends_on:
      - web
  rabbit:
    hostname: rabbit
    image: rabbitmq
    expose:
      - "5672"
      - "15672"
  # Celery worker
  worker:
    build: ./web
    command: ./celery/run_celery.sh
    volumes:
      - .:/code
    links:
      - db
      - rabbit
    depends_on:
      - rabbit  
