version: '2'
services:
  db:
    image: postgres

  web:
    build: .      
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    volumes_from:
      - web
    links:
      - web:web
