version: '2'
services:
  db:
    image: postgres
  web:
    build: . 
    command: ./run_web.sh
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - rabbit
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    volumes_from:
      - web
    links:
      - web:web

#  worker:
 #   build: ./celery      
  #  command: ./run_celery.sh
   # volumes:
   #   - .:/app
  #  links:
   #   - db
    #  - rabbit
   # depends_on:
  #    - rabit
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

